version: '3'
services:
  web_app:
    container_name: web_app
    restart: always
    build: . # m0tei/webRegistryApp:latest
    networks:
      - db_network
    ports:
      - '5000:5000'
    environment:
      - MONGO_DB_HOST = mongo
    volumes:
      - type: volume
        source: app_data
        target: /app
  
  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    networks:
      - db_network
    volumes:
      - type: volume
        source: db_data
        target: /data/db
      - type: volume
        source: db_config
        target: /data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: tpopoviciu_admin
      MONGO_INITDB_ROOT_PASSWORD: tpopoiciu_db_admin_pass

volumes:
  db_data:
    driver: local
  db_config:
    driver: local
  app_data:
    driver: local

networks:
  db_network:
    name: db_network