version: '3'
services:
  web_app:
    container_name: web_app
    restart: always
    build: . # m0tei/webRegistryApp:latest
    networks:
      - db_network
    ports:
      - '5000:5000'
    environment:
      - MONGO_DB_HOST = mongo
    volumes:
      - type: volume
        source: app_data
        target: /app
  
  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    networks:
      - db_network
    volumes:
      - type: volume
        source: db_data
        target: /data/db
      - type: volume
        source: db_config
        target: /data/configdb
    
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    networks:
      - db_network
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME = ambiance
      - ME_CONFIG_MONGODB_SERVER = mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME = tpopoviciu
      - ME_CONFIG_MONGODB_ADMINPASSWORD = tpopoviciu_db_pass


volumes:
  db_data:
    driver: local
  db_config:
    driver: local
  app_data:
    driver: local

networks:
  db_network:
    name: db_network
    driver: bridge