version: '3.9'
services:
  web_app:
    container_name: web_app
    restart: always
    image: m0tei/registru_web:dev
    networks:
      - db_network
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      - TZ=Europe/Bucharest
    volumes:
      - type: volume
        source: app_data
        target: /app
  
  mongo:
    image: mongo:5.0
    container_name: mongo_db
    restart: always
    networks:
      - db_network
    volumes:
      - type: volume
        source: db_data
        target: /data/db
      - type: volume
        source: db_config
        target: /data/configdb
    
  mongo_express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    networks:
      - db_network
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=tpopoviciu
      - ME_CONFIG_MONGODB_ADMINPASSWORD=tpopoviciu_db_pass

  mongo_backup:
    image: m0tei/mongo_backup:0.0.2
    container_name: mongo_backup
    restart: always
    networks:
      - db_network
    volumes:
      - type: volume
        source: db_backup
        target: /backup
    environment:
      - TZ=Europe/Bucharest
      - MONGO_DB_HOST=mongo_db
      - MONGO_DB_USER=tpopoviciu
      - MONGO_DB_PASS=tpopoviciu_db_pass
      - MONGO_DB_NUM=5
      - CRON_TIME=* * * * *


volumes:
  db_data:
    driver: local
  db_config:
    driver: local
  db_backup:
    driver: local
  app_data:
    driver: local

networks:
  db_network:
    name: db_network
    driver: bridge